### PR TITLE
Stop searching usages after first correct match is found.

### PR DESCRIPTION
**Pull request by ideadapt**

### CODE REVIEW

**Comment by kaiza** [comment]
Thanks for the fix. Published to npm as 1.3.5

**Comment by ideadapt** [comment]
Are you aware about the consequences of your change to the foreach thing? did you read my commit message?

**Comment by kaiza** [comment]
Yeah it should behave the same as your code but be slightly more efficient. The outer 'some' will short-circuit once it's found the first true. The forEach version will still iterate over every element even if it's found a true value from the inner 'some'.

**Comment by ideadapt** [comment]
I think 'some' would only be more efficient, if you don't require an Array.from beforehand. Because Array.from iterates the whole array anyway. So worst case scenario is O(n^2), where a simple forEach with a return statement is still O(n).

Btw in a best case scenario forEach still seems to be slightly faster than Array.from, see https://jsperf.com/array-from-map-keys-vs-map-foreach.

**Comment by kaiza** [comment]
Good point about the Array.from. I'll take another look. But it wouldn't be O(n^2), both implementations for the outer loop would be O(n). With my implementation in the worst case it would go through the array twice, not n^2 times.

**Comment by ideadapt** [comment]
you are right. its 2*n sorry for that typo :)

Kai Gorman <notifications@github.com> schrieb am Do., 5. Juli 2018, 08:50:

**Comment by kaiza** [comment]
It would be nice if IterableIterator had a 'some' method. I guess the most efficient would actually be a while loop.

**Pull request merged**
