### PR TITLE
New rule: expect-length

### PR DESCRIPTION
**Pull request by ideadapt**
This new rule checks whether an array variable, which is called forEach on, is checked for its length.

### CODE REVIEW

**Comment by kaiza** [comment]
I'm getting the following errors when I run 'tsc' with your changes:

C:\Code\tslint-jasmine-rules>npm run tsc

> tslint-jasmine-rules@1.3.2 tsc C:\Code\tslint-jasmine-rules
> tsc

node_modules/tsutils/typeguard/node.d.ts(29,74): error TS2694: Namespace 'ts' has no exported member 'ConditionalTypeNode'.
node_modules/tsutils/typeguard/node.d.ts(69,68): error TS2694: Namespace 'ts' has no exported member 'InferTypeNode'.
node_modules/tsutils/typeguard/type.d.ts(2,70): error TS2694: Namespace 'ts' has no exported member 'ConditionalType'.
node_modules/tsutils/typeguard/type.d.ts(7,71): error TS2694: Namespace 'ts' has no exported member 'InstantiableType'.
node_modules/tsutils/typeguard/type.d.ts(12,71): error TS2694: Namespace 'ts' has no exported member 'SubstitutionType'.

**Comment by kaiza** [comment]
Also would you be able to update the README file with your new rule?

**Comment by ideadapt** [comment]
Hi Kaiza
Thanks for your feedback. I just updated the README. But I can not reproduce your build failure. I have tsc version 2.9.2 installed. Do you have a different one?

**Comment by kaiza** [comment]
Updated the typescript dependency to 2.9.2 which fixed it. Published to npm as 1.3.4

**Comment by kaiza** [comment]
ideadapt, I just tried the new rule out and I'm getting false positives. It fails even if I add the length check. Is it working as expected for you?

**Comment by ideadapt** [comment]
@kaiza can you provide me some more details? e.g. the code snippet?

**Comment by kaiza** [comment]
@ideadapt I can't reproduce the false positive I got the other day, but now this doesn't fail when it should:

```
    const test = <any>{};
    test.forEach(x => x);
```

**Comment by kaiza** [comment]
@ideadapt Ignore that last comment if you saw it, I've deleted it. My editor was playing tricks on me and my tslint.json hadn't actually saved. Anyway, this fails for me when it shouldn't:

```
  it('should create', () => {
    const test = <any>{};
    expect(test.length).toBeGreaterThan(0);
    test.forEach(x => x);
  });
```

**Comment by ideadapt** [comment]
@kaiza Ok now I can reproduce the failure. I am going to fix it asap.

**Pull request merged**
