### PR TITLE
feat: skip auto-fix for warnings

### PR DESCRIPTION
**Pull request by aleclarson**
Follow-up to #16

### CODE REVIEW

**Comment by kaiza** [comment]
Thanks will take a look later - at work busy with a few other things at the moment.

**Comment by kaiza** [comment]
@aleclarson I tried to add a unit test for your changes but couldn't get it working. `options.severity` always ends up being `undefined` when I try to configure it like this:

```
    "no-disabled-tests": {
      "severity": "warning"
    }
```

Can you add a test and see if you can get it to work?

**Comment by aleclarson** [comment]
The rule severity is not included with `getOptions`, and the `ruleSeverity` property has `protected` access, so we'll need to pass it into the `CallExpressionWalker` explicitly.

**Comment by aleclarson** [comment]
Added a test and it passes. LGTM 👍

**Pull request merged**
